
[[pages]]
path = "pages/home.py"
name = "Home"
icon = "🏠"

[[pages]]
name = "Image Processing"
is_section = true
icon = ":file_folder:"

[[pages]]
path = "pages/img_process_sMRI.py"
name = "DLMUSE"
icon = ":black_small_square:"

[[pages]]
name = "Data Analytics"
is_section = true
icon = ":file_folder:"

[[pages]]
path = "pages/workflow_sMRI.py"
name = "sMRI Workflow"
icon = ":black_small_square:"

[[pages]]
name = "Visualizations"
is_section = true
icon = ":file_folder:"

[[pages]]
path = "pages/view_plot_data.py"
name = "Plot Data"
icon = ":black_small_square:"

[[pages]]
path = "pages/view_plot_centiles.py"
name = "Plot Centiles"
icon = ":black_small_square:"

[[pages]]
path = "pages/view_plot_subject.py"
name = "Plot Subject"
icon = ":black_small_square:"

[[pages]]
path = "pages/view_img.py"
name = "View Image"
icon = ":black_small_square:"

