
[[pages]]
path = "pages/home.py"
name = "Home"
icon = "🏠"

[[pages]]
name = "Image Processing"
is_section = true
icon = ":file_folder:"

[[pages]]
path = "pages/process_sMRI_DLMUSE.py"
name = "DLMUSE (sMRI)"
icon = ":black_small_square:"

[[pages]]
path = "pages/process_DTI_DTIPrep.py"
name = "DTIPrep (DTI)"
icon = ":black_small_square:"

[[pages]]
name = "Data Analytics"
is_section = true
icon = ":file_folder:"

[[pages]]
path = "pages/workflow_sMRI_MLScores.py"
name = "ML Biomarkers (sMRI)"
icon = ":black_small_square:"

[[pages]]
name = "Visualizations"
is_section = true
icon = ":file_folder:"

[[pages]]
path = "pages/view_sMRI_plot_vars_all.py"
name = "Plot Variables - Study (sMRI)"
icon = ":black_small_square:"

[[pages]]
path = "pages/view_sMRI_plot_centiles.py"
name = "Plot Centiles (sMRI)"
icon = ":black_small_square:"

[[pages]]
path = "pages/view_sMRI_plot_vars_single.py"
name = "Plot Variables - Individual (sMRI)"
icon = ":black_small_square:"

[[pages]]
path = "pages/view_sMRI_DLMUSE.py"
name = "View DLMUSE (sMRI)"
icon = ":black_small_square:"

