
[[pages]]
path = "pages/home.py"
name = "Home"
icon = "🏠"

[[pages]]
name = "MRI Preparation"
is_section = true
icon = ":file_folder:"

[[pages]]
path = "pages/prep_sMRI_dicomtonifti.py"
name = "Dicom to Nifti (sMRI, DTI, fMRI)"
icon = ":black_small_square:"

[[pages]]
name = "Image Processing"
is_section = true
icon = ":file_folder:"

[[pages]]
path = "pages/process_sMRI_DLMUSE.py"
name = "DLMUSE (sMRI)"
icon = ":black_small_square:"

[[pages]]
name = "Data Analytics"
is_section = true
icon = ":file_folder:"

[[pages]]
path = "pages/workflow_sMRI_MLScores.py"
name = "ML Biomarkers (sMRI)"
icon = ":black_small_square:"

[[pages]]
name = "Visualizations"
is_section = true
icon = ":file_folder:"

[[pages]]
path = "pages/view_sMRI_plot_vars_all.py"
name = "Study Data (sMRI)"
icon = ":black_small_square:"

[[pages]]
path = "pages/view_sMRI_plot_vars_single.py"
name = "Participant Data (sMRI)"
icon = ":black_small_square:"

[[pages]]
path = "pages/view_sMRI_DLMUSE.py"
name = "View Images (sMRI)"
icon = ":black_small_square:"

