name: Pipeline test cases for ubuntu

# workflow dispatch has been added for testing purposes
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ["ubuntu-latest"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: Set-up miniconda for macos and ubuntu
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
          miniconda-version: "latest"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: pipeline test for vTest1 using spare
        run: |
          python3 run.py --folder 1 --cores 4 --no_conda 0
